const SECTION_IDS = ['home', 'stats', 'about', 'packages', 'gallery', 'testimonials', 'contact'];

document.addEventListener('DOMContentLoaded', () => {
    initSectionView();
    initNavbar();
    initMobileMenu();
    initDynamicGallery();   // build the gallery DOM first...
    initScrollReveal();     // ...so reveal-on-scroll picks up the new items...
    initGalleryLightbox();  // ...and the lightbox has something to wire up
    initStatsCounter();
    initTestimonialSlider();
    initContactForm();
    initBackToTop();
    initBrandIcon();
});

// Builds the gallery from images/gallery-data.js (auto-generated by update-gallery.js,
// which scans images/gallery/<category>/ folders) — any number of photos per category.
function initDynamicGallery() {
    const container = document.getElementById('galleryDynamic');
    if (!container || typeof GALLERY_DATA === 'undefined') return;

    const CATEGORIES = [
        { key: 'hall', label: 'Our Hall & Studio' },
        { key: 'owner', label: 'Meet the Owner' },
        { key: 'events', label: 'Events at 9 Star' },
        { key: 'singers', label: 'Our Star Singers' },
        { key: 'random', label: 'More Moments' },
    ];

    const escapeHtml = str => str.replace(/[&<>"']/g, c => ({
        '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
    }[c]));

    let html = '';
    CATEGORIES.forEach(({ key, label }) => {
        const photos = GALLERY_DATA[key] || [];
        html += '<div class="gallery-category reveal">';
        html += `<h3 class="gallery-category-title">${label}</h3>`;

        if (photos.length) {
            html += '<div class="gallery-grid">';
            photos.forEach((src, i) => {
                const safeSrc = escapeHtml(src);
                html += `
                    <div class="gallery-item" style="--i:${(i % 6) + 1}" data-caption="${label}">
                        <img src="${safeSrc}" alt="${escapeHtml(label)}" loading="lazy">
                    </div>`;
            });
            html += '</div>';
        } else {
            html += '<p class="gallery-empty">Photos coming soon.</p>';
        }

        html += '</div>';
    });

    container.innerHTML = html;
}

// Home shows the full page; every other nav target shows only that one section
function initSectionView() {
    function showView(target) {
        const isHome = target === 'home' || !SECTION_IDS.includes(target);

        SECTION_IDS.forEach(id => {
            const el = document.getElementById(id);
            if (!el) return;
            el.classList.toggle('hidden', !isHome && id !== target);
        });

        document.body.classList.toggle('single-view', !isHome);

        document.querySelectorAll('.nav-link').forEach(link => {
            link.classList.toggle('active', link.getAttribute('href') === `#${target}`);
        });

        // Non-home sections have light backgrounds right under the fixed navbar, so it
        // needs its dark "scrolled" background immediately — don't wait for a scroll event,
        // which may never fire if the page is already at the top.
        document.getElementById('navbar').classList.toggle('scrolled', !isHome || window.scrollY > 40);

        window.scrollTo({ top: 0, behavior: 'smooth' });
    }

    document.querySelectorAll('a[href^="#"]').forEach(link => {
        const id = link.getAttribute('href').slice(1);
        if (!SECTION_IDS.includes(id)) return;
        link.addEventListener('click', e => {
            e.preventDefault();
            showView(id);
            history.replaceState(null, '', `#${id}`);
        });
    });

    const initial = location.hash.slice(1);
    showView(SECTION_IDS.includes(initial) ? initial : 'home');

    window.isHomeView = () => !document.body.classList.contains('single-view');
}

// Sticky navbar background + active link highlighting (only while in the full home view)
function initNavbar() {
    const navbar = document.getElementById('navbar');
    const navLinks = document.querySelectorAll('.nav-link');
    const sections = document.querySelectorAll('#home, #about, #packages, #gallery, #testimonials, #contact');

    const onScroll = () => {
        navbar.classList.toggle('scrolled', window.scrollY > 40 || !window.isHomeView());

        if (!window.isHomeView()) return;

        let current = sections[0]?.id;
        sections.forEach(section => {
            const top = section.offsetTop - 120;
            if (window.scrollY >= top) current = section.id;
        });

        navLinks.forEach(link => {
            link.classList.toggle('active', link.getAttribute('href') === `#${current}`);
        });
    };

    window.addEventListener('scroll', onScroll);
    onScroll();
}

// Mobile hamburger menu
function initMobileMenu() {
    const hamburger = document.getElementById('hamburger');
    const navLinks = document.getElementById('navLinks');

    hamburger.addEventListener('click', () => {
        const isOpen = navLinks.classList.toggle('open');
        hamburger.classList.toggle('active', isOpen);
        hamburger.setAttribute('aria-expanded', isOpen);
    });

    navLinks.querySelectorAll('a').forEach(link => {
        link.addEventListener('click', () => {
            navLinks.classList.remove('open');
            hamburger.classList.remove('active');
            hamburger.setAttribute('aria-expanded', 'false');
        });
    });
}

// Fade/slide elements in as they enter the viewport (also fires when a hidden section is revealed)
function initScrollReveal() {
    const targets = document.querySelectorAll('.reveal');
    const observer = new IntersectionObserver(entries => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.classList.add('visible');
            }
        });
    }, { threshold: 0.15 });

    targets.forEach(target => observer.observe(target));
}

// Animate the stats numbers counting up once visible
function initStatsCounter() {
    const stats = document.querySelectorAll('.stat');
    const animated = new WeakSet();

    const observer = new IntersectionObserver(entries => {
        entries.forEach(entry => {
            if (!entry.isIntersecting || animated.has(entry.target)) return;
            animated.add(entry.target);

            const stat = entry.target;
            const target = Number(stat.dataset.count);
            const counter = stat.querySelector('.counter');
            const duration = 1500;
            const start = performance.now();

            const tick = now => {
                const progress = Math.min((now - start) / duration, 1);
                counter.textContent = Math.floor(progress * target).toLocaleString();
                if (progress < 1) requestAnimationFrame(tick);
                else counter.textContent = target.toLocaleString();
            };

            requestAnimationFrame(tick);
        });
    }, { threshold: 0.4 });

    stats.forEach(stat => observer.observe(stat));
}

// Testimonial carousel with autoplay, dots, and prev/next controls
function initTestimonialSlider() {
    const track = document.getElementById('testimonialTrack');
    const dotsContainer = document.getElementById('testimonialDots');
    const prevBtn = document.getElementById('prevTestimonial');
    const nextBtn = document.getElementById('nextTestimonial');
    const cards = track.children.length;
    let index = 0;
    let autoplay;

    for (let i = 0; i < cards; i++) {
        const dot = document.createElement('span');
        if (i === 0) dot.classList.add('active');
        dot.addEventListener('click', () => goTo(i));
        dotsContainer.appendChild(dot);
    }

    const dots = dotsContainer.children;

    function goTo(i) {
        index = (i + cards) % cards;
        track.style.transform = `translateX(-${index * 100}%)`;
        Array.from(dots).forEach((dot, di) => dot.classList.toggle('active', di === index));
    }

    function startAutoplay() {
        autoplay = setInterval(() => goTo(index + 1), 5000);
    }

    prevBtn.addEventListener('click', () => { goTo(index - 1); clearInterval(autoplay); startAutoplay(); });
    nextBtn.addEventListener('click', () => { goTo(index + 1); clearInterval(autoplay); startAutoplay(); });

    startAutoplay();
}

// Simple lightbox for gallery items
function initGalleryLightbox() {
    const allItems = Array.from(document.querySelectorAll('.gallery-item'));
    const lightbox = document.getElementById('lightbox');
    const content = document.getElementById('lightboxContent');
    const closeBtn = document.getElementById('lightboxClose');
    const prevBtn = document.getElementById('lightboxPrev');
    const nextBtn = document.getElementById('lightboxNext');
    let current = 0;

    // Empty slots (image not uploaded yet) get a dashed placeholder and don't open the lightbox
    allItems.forEach(item => {
        const img = item.querySelector('img');
        if (!img) return;
        img.addEventListener('error', () => item.classList.add('empty'), { once: true });
    });

    function filledItems() {
        return allItems.filter(item => !item.classList.contains('empty'));
    }

    function open(i) {
        const items = filledItems();
        if (!items.length) return;
        current = (i + items.length) % items.length;
        const img = items[current].querySelector('img');
        content.innerHTML = '';
        const clone = img.cloneNode();
        clone.style.width = '100%';
        clone.style.height = '100%';
        clone.style.objectFit = 'cover';
        clone.style.borderRadius = 'inherit';
        content.appendChild(clone);
        lightbox.classList.add('open');
    }

    function close() {
        lightbox.classList.remove('open');
    }

    allItems.forEach(item => item.addEventListener('click', () => {
        if (item.classList.contains('empty')) return;
        open(filledItems().indexOf(item));
    }));
    closeBtn.addEventListener('click', close);
    lightbox.addEventListener('click', e => { if (e.target === lightbox) close(); });
    prevBtn.addEventListener('click', () => open(current - 1));
    nextBtn.addEventListener('click', () => open(current + 1));

    document.addEventListener('keydown', e => {
        if (!lightbox.classList.contains('open')) return;
        if (e.key === 'Escape') close();
        if (e.key === 'ArrowLeft') open(current - 1);
        if (e.key === 'ArrowRight') open(current + 1);
    });
}

// Client-side validation + real submit to FormSubmit (emails the enquiry to the hall's inbox)
function initContactForm() {
    const form = document.getElementById('contactForm');
    const success = document.getElementById('formSuccess');
    const errorMsg = document.getElementById('formError');

    const validators = {
        name: value => value.trim().length >= 2 || 'Please enter your name.',
        email: value => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value) || 'Enter a valid email address.',
        message: value => value.trim().length >= 10 || 'Message should be at least 10 characters.'
    };

    function validateField(field) {
        const rule = validators[field.name];
        if (!rule) return true;
        const result = rule(field.value);
        const errorEl = field.parentElement.querySelector('.error-msg');
        if (result === true) {
            field.classList.remove('invalid');
            if (errorEl) errorEl.textContent = '';
            return true;
        }
        field.classList.add('invalid');
        if (errorEl) errorEl.textContent = result;
        return false;
    }

    form.querySelectorAll('input, textarea').forEach(field => {
        field.addEventListener('blur', () => validateField(field));
        field.addEventListener('input', () => {
            if (field.classList.contains('invalid')) validateField(field);
        });
    });

    form.addEventListener('submit', async e => {
        e.preventDefault();
        success.classList.remove('show');
        errorMsg.classList.remove('show');

        const fields = Array.from(form.querySelectorAll('input[name], textarea[name]'));
        const allValid = fields.reduce((valid, field) => validateField(field) && valid, true);
        if (!allValid) return;

        const submitBtn = form.querySelector('button[type="submit"]');
        submitBtn.disabled = true;
        submitBtn.textContent = 'Sending...';

        try {
            const response = await fetch(form.action, {
                method: 'POST',
                body: new FormData(form),
                headers: { Accept: 'application/json' }
            });

            if (!response.ok) throw new Error('Request failed');

            success.classList.add('show');
            form.reset();
        } catch (err) {
            errorMsg.classList.add('show');
        } finally {
            submitBtn.disabled = false;
            submitBtn.textContent = 'Send Enquiry';
        }
    });
}

// Back-to-top button
function initBackToTop() {
    const btn = document.getElementById('backToTop');
    window.addEventListener('scroll', () => {
        btn.classList.toggle('show', window.scrollY > 500);
    });
    btn.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));
}

// Star badge: horizontal flip on click, or on a right swipe on touch devices.
// Shine sweep only added if the browser actually supports element masking, so
// there's never a silent "invisible icon" failure mode.
function initBrandIcon() {
    const wrap = document.querySelector('.banner-icon-wrap');
    const icon = document.querySelector('.banner-icon');
    if (!wrap || !icon) return;

    const spin = (direction = 'right') => {
        icon.classList.remove('spinning-right', 'spinning-left');
        void icon.offsetWidth; // restart the animation even on repeated triggers
        icon.classList.add(direction === 'left' ? 'spinning-left' : 'spinning-right');
    };

    icon.addEventListener('click', () => spin('right'));
    icon.addEventListener('animationend', () => icon.classList.remove('spinning-right', 'spinning-left'));

    let touchStartX = 0, touchStartY = 0;
    icon.addEventListener('touchstart', e => {
        touchStartX = e.changedTouches[0].clientX;
        touchStartY = e.changedTouches[0].clientY;
    }, { passive: true });

    icon.addEventListener('touchend', e => {
        const dx = e.changedTouches[0].clientX - touchStartX;
        const dy = e.changedTouches[0].clientY - touchStartY;
        const isHorizontalSwipe = Math.abs(dx) > 35 && Math.abs(dx) > Math.abs(dy) * 1.5;
        if (isHorizontalSwipe) spin(dx > 0 ? 'right' : 'left');
    }, { passive: true });

    const supportsMask =
        (window.CSS && CSS.supports && (CSS.supports('mask-image', 'url(x)') || CSS.supports('-webkit-mask-image', 'url(x)')));

    if (supportsMask) {
        const shine = document.createElement('span');
        shine.className = 'banner-icon-shine';
        shine.setAttribute('aria-hidden', 'true');
        wrap.appendChild(shine);
    }
}
