// Scans images/gallery/<category>/ folders and writes images/gallery-data.js
// listing whatever photos it finds — no limit on how many. Run this again
// (double-click update-gallery.bat) any time after adding or removing photos.

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const GALLERY_DIR = path.join(ROOT, 'images', 'gallery');

const CATEGORIES = [
    { key: 'hall', label: 'Our Hall & Studio' },
    { key: 'owner', label: 'Meet the Owner' },
    { key: 'events', label: 'Events at 9 Star' },
    { key: 'singers', label: 'Our Star Singers' },
    { key: 'random', label: 'More Moments' },
];

const EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];

const data = {};

CATEGORIES.forEach(({ key }) => {
    const dir = path.join(GALLERY_DIR, key);
    fs.mkdirSync(dir, { recursive: true });
    const files = fs.readdirSync(dir)
        .filter(f => EXTENSIONS.includes(path.extname(f).toLowerCase()))
        .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
    data[key] = files.map(f => `images/gallery/${key}/${f}`);
});

const output =
    '// Auto-generated by update-gallery.js — do not edit by hand.\n' +
    '// Run update-gallery.bat again after adding or removing photos.\n' +
    'const GALLERY_DATA = ' + JSON.stringify(data, null, 4) + ';\n';

fs.writeFileSync(path.join(GALLERY_DIR, '..', 'gallery-data.js'), output);

const total = Object.values(data).reduce((n, arr) => n + arr.length, 0);
console.log(`Gallery updated -- ${total} photo(s) found:`);
CATEGORIES.forEach(({ key, label }) => console.log(`  ${label}: ${data[key].length}`));
