// Auto-generated by update-gallery.js — do not edit by hand.
// Run update-gallery.bat again after adding or removing photos.
const GALLERY_DATA = {
    "hall": [
        "images/gallery/hall/9starlogo.png",
        "images/gallery/hall/1000391871.jpg",
        "images/gallery/hall/1000391872.jpg",
        "images/gallery/hall/1000391873.jpg"
    ],
    "owner": [
        "images/gallery/owner/WhatsApp Image 2026-08-03 at 20.18.05.jpeg",
        "images/gallery/owner/WhatsApp Image 2026-08-06 at 14.29.47 (1).jpeg",
        "images/gallery/owner/WhatsApp Image 2026-08-06 at 14.29.47.jpeg",
        "images/gallery/owner/WhatsApp Image 2026-08-06 at 21.04.30.jpeg",
        "images/gallery/owner/WhatsApp Image 2026-08-06 at 21.12.47.jpeg",
        "images/gallery/owner/WhatsApp Image 2026-08-06 at 21.19.55.jpeg",
        "images/gallery/owner/WhatsApp Image 2026-08-06 at 21.20.29.jpeg"
    ],
    "events": [
        "images/gallery/events/WhatsApp Image 2026-08-06 at 21.02.07.jpeg",
        "images/gallery/events/WhatsApp Image 2026-08-06 at 21.03.01 (1).jpeg",
        "images/gallery/events/WhatsApp Image 2026-08-06 at 21.03.01 (2).jpeg",
        "images/gallery/events/WhatsApp Image 2026-08-06 at 21.03.01.jpeg"
    ],
    "singers": [
        "images/gallery/singers/IMG_20220226_012605_627.jpg",
        "images/gallery/singers/WhatsApp Image 2026-08-02 at 15.45.00.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-02 at 15.45.01 (1).jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-02 at 15.45.01.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-03 at 16.17.38.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-03 at 20.17.45.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-03 at 20.17.46.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 14.29.43 (1).jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 14.29.43.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 14.29.48 (1).jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 14.29.48 (2).jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 14.29.48.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 14.29.49.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 14.31.45 (1).jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 14.31.45.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 14.31.46.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 20.46.10.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 20.50.44.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 20.54.14.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 21.00.57.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 21.03.16.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 21.10.14.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 21.12.47 (1).jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 21.34.14.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 21.37.07.jpeg",
        "images/gallery/singers/WhatsApp Image 2026-08-06 at 21.39.17.jpeg"
    ],
    "random": []
};
